# config
cover: /img/夜景1.jpg
logo: /img/logo.png
top_saying:
- title: <span>接受</span>，<span>改变</span>，<span>欣喜</span>
- content: ————WELCOME
bottom_saying: 虽然还没想好写点什么，但是总觉得这里放句话比较和谐。
# Content
excerpt_link: 更多

rss: /atom.xml

highlightjs: vs

#Works
works:
- works_name: 我的github
  works_url: https://github.com/wangxiangyao
- works_name: BBB
  works_url: /atom.xml

#duoshuo name
duoshuo: wangxiangyao

#disqus name
disqus_shortname:

#fancybox
fancybox: true

# Miscellaneous
github: https://github.com/
twitter: https://twitter.com/
facebook: https://www.facebook.com/
google: https://google.com/
weibo: http://weibo.com/

#about  timeline
timeline:
- num: 1
  word: 2017/01/01-Start
- num: 2
  word: 2014/11/29-XXX
- num: 3
  word: 2015/02/18-DDD
- num: 4
  word: More

#Links
links:
- name: Kieran-这个主题的作者
  link: http://go.kieran.top/